services:
  client:
    image: node:20.8.0
    working_dir: /client
    volumes:
      - ./client:/client
      - client-node-modules:/client/node_modules

  nginx:
    image: tf01-nginx:local
    build:
      context: .
      args:
        BUILD_ENV: local
    platform: linux/amd64
    ports:
      - "8080:80"

volumes:
  client-node-modules:
