server {
  listen 80;

  location = / {
    proxy_pass http://floci:4566/my-bucket-949926374137-ap-northeast-1-an/index.html;
  }

  location / {
    proxy_pass http://floci:4566/my-bucket-949926374137-ap-northeast-1-an/;
  }
}
